base:
  name: everyone-chatgpt
  key: 4a%#3&$ADRfad%$#fasd32 #请求的加密KEY

#Http请求重试机制
resty:
  time_out: 120 #超时时间，单位：秒
  retry_count: 5 #重试次数
  retry_wait_time: 60 #重试等待时间，单位：秒
  retry_max_wait_time: 90 #重试最大等待时间，单位：秒

mysql:
  master: #主库
    host: test.mysql.ruigushop.com
    port: 3306
    user: ruigu
    pass: ruigu
    db: agent_platform_db
    charset: utf8mb4
  slave: #从库
    host: test.mysql.ruigushop.com
    port: 3306
    user: ruigu
    pass: ruigu
    db: agent_platform_db
    charset: utf8mb4

redis:
  host: test.pub-redis.ruigushop.com
  port: 6379
  db: 0
  auth: h0ScbctSdA

rabbit:
  default:
    host: test.rabbitmq.ruigushop.com
    user: guest
    pass: guest
    port: 5672
    vhost: /diablo
    heartbeat: 15 #心跳，单位：秒

email:
  host: smtp.mxhichina.com
  email: system@ruigushop.com
  username: system@ruigushop.com
  password: oxedYa3sQckk2f
  port: 25